export const site = {
  name: "Summit Roofing & Exterior",
  legalName: "Summit Roofing & Exterior LLC",
  tagline: "Roofing Built to Last",
  url: "https://www.summitroofingexterior.com",
  phone: "(555) 214-7663",
  phoneHref: "tel:+15552147663",
  email: "hello@summitroofingexterior.com",
  address: {
    street: "4820 Ridgeline Parkway, Suite 200",
    city: "Denver",
    state: "CO",
    zip: "80216",
  },
  hours: [
    { days: "Monday – Friday", time: "7:00 AM – 6:00 PM" },
    { days: "Saturday", time: "8:00 AM – 2:00 PM" },
    { days: "Sunday", time: "Emergency service only" },
  ],
  emergency: "24/7 Emergency Storm Response",
  license: "Licensed, Bonded & Insured · CO License #RC-004821",
  social: {
    facebook: "https://facebook.com/summitroofingexterior",
    instagram: "https://instagram.com/summitroofingexterior",
    google: "https://g.page/summitroofingexterior",
  },
  stats: {
    yearsExperience: 22,
    projectsCompleted: 4800,
    fiveStarReviews: 1250,
    warrantyYears: 50,
  },
  serviceAreas: [
    "Denver",
    "Aurora",
    "Lakewood",
    "Arvada",
    "Westminster",
    "Centennial",
    "Thornton",
    "Highlands Ranch",
    "Littleton",
    "Broomfield",
    "Parker",
    "Castle Rock",
  ],
} as const;
